// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/kebin6/simple-douyin-rpc/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/kebin6/simple-douyin-rpc/ent/douyin"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Douyin is the client for interacting with the Douyin builders.
	Douyin *DouyinClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Douyin = NewDouyinClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Douyin: NewDouyinClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Douyin: NewDouyinClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Douyin.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Douyin.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Douyin.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DouyinMutation:
		return c.Douyin.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DouyinClient is a client for the Douyin schema.
type DouyinClient struct {
	config
}

// NewDouyinClient returns a client for the Douyin from the given config.
func NewDouyinClient(c config) *DouyinClient {
	return &DouyinClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `douyin.Hooks(f(g(h())))`.
func (c *DouyinClient) Use(hooks ...Hook) {
	c.hooks.Douyin = append(c.hooks.Douyin, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `douyin.Intercept(f(g(h())))`.
func (c *DouyinClient) Intercept(interceptors ...Interceptor) {
	c.inters.Douyin = append(c.inters.Douyin, interceptors...)
}

// Create returns a builder for creating a Douyin entity.
func (c *DouyinClient) Create() *DouyinCreate {
	mutation := newDouyinMutation(c.config, OpCreate)
	return &DouyinCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Douyin entities.
func (c *DouyinClient) CreateBulk(builders ...*DouyinCreate) *DouyinCreateBulk {
	return &DouyinCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DouyinClient) MapCreateBulk(slice any, setFunc func(*DouyinCreate, int)) *DouyinCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DouyinCreateBulk{err: fmt.Errorf("calling to DouyinClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DouyinCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DouyinCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Douyin.
func (c *DouyinClient) Update() *DouyinUpdate {
	mutation := newDouyinMutation(c.config, OpUpdate)
	return &DouyinUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DouyinClient) UpdateOne(d *Douyin) *DouyinUpdateOne {
	mutation := newDouyinMutation(c.config, OpUpdateOne, withDouyin(d))
	return &DouyinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DouyinClient) UpdateOneID(id int) *DouyinUpdateOne {
	mutation := newDouyinMutation(c.config, OpUpdateOne, withDouyinID(id))
	return &DouyinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Douyin.
func (c *DouyinClient) Delete() *DouyinDelete {
	mutation := newDouyinMutation(c.config, OpDelete)
	return &DouyinDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DouyinClient) DeleteOne(d *Douyin) *DouyinDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DouyinClient) DeleteOneID(id int) *DouyinDeleteOne {
	builder := c.Delete().Where(douyin.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DouyinDeleteOne{builder}
}

// Query returns a query builder for Douyin.
func (c *DouyinClient) Query() *DouyinQuery {
	return &DouyinQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDouyin},
		inters: c.Interceptors(),
	}
}

// Get returns a Douyin entity by its id.
func (c *DouyinClient) Get(ctx context.Context, id int) (*Douyin, error) {
	return c.Query().Where(douyin.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DouyinClient) GetX(ctx context.Context, id int) *Douyin {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DouyinClient) Hooks() []Hook {
	return c.hooks.Douyin
}

// Interceptors returns the client interceptors.
func (c *DouyinClient) Interceptors() []Interceptor {
	return c.inters.Douyin
}

func (c *DouyinClient) mutate(ctx context.Context, m *DouyinMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DouyinCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DouyinUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DouyinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DouyinDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Douyin mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Douyin []ent.Hook
	}
	inters struct {
		Douyin []ent.Interceptor
	}
)
