// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kebin6/simple-douyin-rpc/ent/douyin"
)

// Douyin is the model entity for the Douyin schema.
type Douyin struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Douyin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case douyin.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Douyin fields.
func (d *Douyin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case douyin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Douyin.
// This includes values selected through modifiers, order, etc.
func (d *Douyin) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// Update returns a builder for updating this Douyin.
// Note that you need to call Douyin.Unwrap() before calling this method if this Douyin
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Douyin) Update() *DouyinUpdateOne {
	return NewDouyinClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Douyin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Douyin) Unwrap() *Douyin {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Douyin is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Douyin) String() string {
	var builder strings.Builder
	builder.WriteString("Douyin(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Douyins is a parsable slice of Douyin.
type Douyins []*Douyin
